language: node_js
node_js:
- '0.12'
before_script:
- npm install -g gulp bower
script: gulp deploy
notifications:
  email:
    recipients:
      - david@dmarby.se
    on_success: change
    on_failure: always